/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DropsRouteImport } from './routes/drops'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PagamentoPendenteRouteImport } from './routes/pagamento/pendente'
import { Route as PagamentoRecusadoRouteImport } from './routes/pagamento/recusado'
import { Route as PagamentoSucessoRouteImport } from './routes/pagamento/sucesso'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as ApiWebhookMercadopagoRouteImport } from './routes/api/webhook/mercadopago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsRoute = DropsRouteImport.update({
  id: '/drops',
  path: '/drops',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoPendenteRoute = PagamentoPendenteRouteImport.update({
  id: '/pagamento/pendente',
  path: '/pagamento/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRecusadoRoute = PagamentoRecusadoRouteImport.update({
  id: '/pagamento/recusado',
  path: '/pagamento/recusado',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoSucessoRoute = PagamentoSucessoRouteImport.update({
  id: '/pagamento/sucesso',
  path: '/pagamento/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookMercadopagoRoute = ApiWebhookMercadopagoRouteImport.update({
  id: '/api/webhook/mercadopago',
  path: '/api/webhook/mercadopago',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/drops': typeof DropsRoute
  '/loja': typeof LojaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/pagamento/pendente': typeof PagamentoPendenteRoute
  '/pagamento/recusado': typeof PagamentoRecusadoRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/webhook/mercadopago': typeof ApiWebhookMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/drops': typeof DropsRoute
  '/loja': typeof LojaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/pagamento/pendente': typeof PagamentoPendenteRoute
  '/pagamento/recusado': typeof PagamentoRecusadoRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/webhook/mercadopago': typeof ApiWebhookMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/drops': typeof DropsRoute
  '/loja': typeof LojaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/pagamento/pendente': typeof PagamentoPendenteRoute
  '/pagamento/recusado': typeof PagamentoRecusadoRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/webhook/mercadopago': typeof ApiWebhookMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/drops'
    | '/loja'
    | '/sitemap.xml'
    | '/sobre'
    | '/pagamento/pendente'
    | '/pagamento/recusado'
    | '/pagamento/sucesso'
    | '/produto/$slug'
    | '/api/webhook/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/drops'
    | '/loja'
    | '/sitemap.xml'
    | '/sobre'
    | '/pagamento/pendente'
    | '/pagamento/recusado'
    | '/pagamento/sucesso'
    | '/produto/$slug'
    | '/api/webhook/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/drops'
    | '/loja'
    | '/sitemap.xml'
    | '/sobre'
    | '/pagamento/pendente'
    | '/pagamento/recusado'
    | '/pagamento/sucesso'
    | '/produto/$slug'
    | '/api/webhook/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  DropsRoute: typeof DropsRoute
  LojaRoute: typeof LojaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  PagamentoPendenteRoute: typeof PagamentoPendenteRoute
  PagamentoRecusadoRoute: typeof PagamentoRecusadoRoute
  PagamentoSucessoRoute: typeof PagamentoSucessoRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiWebhookMercadopagoRoute: typeof ApiWebhookMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops': {
      id: '/drops'
      path: '/drops'
      fullPath: '/drops'
      preLoaderRoute: typeof DropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/pendente': {
      id: '/pagamento/pendente'
      path: '/pagamento/pendente'
      fullPath: '/pagamento/pendente'
      preLoaderRoute: typeof PagamentoPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/recusado': {
      id: '/pagamento/recusado'
      path: '/pagamento/recusado'
      fullPath: '/pagamento/recusado'
      preLoaderRoute: typeof PagamentoRecusadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/sucesso': {
      id: '/pagamento/sucesso'
      path: '/pagamento/sucesso'
      fullPath: '/pagamento/sucesso'
      preLoaderRoute: typeof PagamentoSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/mercadopago': {
      id: '/api/webhook/mercadopago'
      path: '/api/webhook/mercadopago'
      fullPath: '/api/webhook/mercadopago'
      preLoaderRoute: typeof ApiWebhookMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  DropsRoute: DropsRoute,
  LojaRoute: LojaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  PagamentoPendenteRoute: PagamentoPendenteRoute,
  PagamentoRecusadoRoute: PagamentoRecusadoRoute,
  PagamentoSucessoRoute: PagamentoSucessoRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiWebhookMercadopagoRoute: ApiWebhookMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
